### ISSUE TITLE
Collections missing `maxSupply`

### ISSUE THREAD

**Issue by Yuripetusko** [subsquid/uniques-squid#1]
When creating a uniques collection you can now specify `maxSupply` which will ensure that no more than this number of NFTs can be minted in this collection, we should index this value on collection.

`api.query.uniques.collectionMaxSupply`

**Comment by Yuripetusko** [comment]
The event is `CollectionMaxSupplySet`

https://github.com/paritytech/substrate/blob/a47f200eebeb88a5bde6f1ed2be9728b82536dde/frame/uniques/src/lib.rs#L1430

**Comment by ma-shulgin** [comment]
https://github.com/subsquid/uniques-squid/pull/4

**Comment by Yuripetusko** [comment]
I still don't see this field in graphql @ma-shulgin
